package com.cdlixin.coc.model.greendaogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cdlixin.coc.entity.ChannelItem;
import com.cdlixin.coc.entity.NewsEntity;
import com.cdlixin.coc.entity.UserEntity;
import com.cdlixin.coc.entity.OrgEntity;

import com.cdlixin.coc.model.greendaogen.ChannelItemDao;
import com.cdlixin.coc.model.greendaogen.NewsEntityDao;
import com.cdlixin.coc.model.greendaogen.UserEntityDao;
import com.cdlixin.coc.model.greendaogen.OrgEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelItemDaoConfig;
    private final DaoConfig newsEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig orgEntityDaoConfig;

    private final ChannelItemDao channelItemDao;
    private final NewsEntityDao newsEntityDao;
    private final UserEntityDao userEntityDao;
    private final OrgEntityDao orgEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelItemDaoConfig = daoConfigMap.get(ChannelItemDao.class).clone();
        channelItemDaoConfig.initIdentityScope(type);

        newsEntityDaoConfig = daoConfigMap.get(NewsEntityDao.class).clone();
        newsEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        orgEntityDaoConfig = daoConfigMap.get(OrgEntityDao.class).clone();
        orgEntityDaoConfig.initIdentityScope(type);

        channelItemDao = new ChannelItemDao(channelItemDaoConfig, this);
        newsEntityDao = new NewsEntityDao(newsEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        orgEntityDao = new OrgEntityDao(orgEntityDaoConfig, this);

        registerDao(ChannelItem.class, channelItemDao);
        registerDao(NewsEntity.class, newsEntityDao);
        registerDao(UserEntity.class, userEntityDao);
        registerDao(OrgEntity.class, orgEntityDao);
    }
    
    public void clear() {
        channelItemDaoConfig.clearIdentityScope();
        newsEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
        orgEntityDaoConfig.clearIdentityScope();
    }

    public ChannelItemDao getChannelItemDao() {
        return channelItemDao;
    }

    public NewsEntityDao getNewsEntityDao() {
        return newsEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public OrgEntityDao getOrgEntityDao() {
        return orgEntityDao;
    }

}
