package com.cdlixin.coc.model.greendaogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cdlixin.coc.entity.ChannelItem;
import com.cdlixin.coc.entity.NewsEntity;

import com.cdlixin.coc.model.greendaogen.ChannelItemDao;
import com.cdlixin.coc.model.greendaogen.NewsEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelItemDaoConfig;
    private final DaoConfig newsEntityDaoConfig;

    private final ChannelItemDao channelItemDao;
    private final NewsEntityDao newsEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelItemDaoConfig = daoConfigMap.get(ChannelItemDao.class).clone();
        channelItemDaoConfig.initIdentityScope(type);

        newsEntityDaoConfig = daoConfigMap.get(NewsEntityDao.class).clone();
        newsEntityDaoConfig.initIdentityScope(type);

        channelItemDao = new ChannelItemDao(channelItemDaoConfig, this);
        newsEntityDao = new NewsEntityDao(newsEntityDaoConfig, this);

        registerDao(ChannelItem.class, channelItemDao);
        registerDao(NewsEntity.class, newsEntityDao);
    }
    
    public void clear() {
        channelItemDaoConfig.clearIdentityScope();
        newsEntityDaoConfig.clearIdentityScope();
    }

    public ChannelItemDao getChannelItemDao() {
        return channelItemDao;
    }

    public NewsEntityDao getNewsEntityDao() {
        return newsEntityDao;
    }

}
